import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

export function useCopy() {
  const { t } = useTranslation()

  return useMemo(
    () => ({
      brand: t('brand'),
      title: t('title'),
      subtitle: t('subtitle'),
      importAudio: t('importAudio'),
      createStarterPack: t('createStarterPack'),
      dropTitle: t('dropTitle'),
      dropHint: t('dropHint'),
      search: t('search'),
      searchPlaceholder: t('searchPlaceholder'),
      backup: t('backup'),
      backupHint: t('backupHint'),
      exportBackup: t('exportBackup'),
      importBackup: t('importBackup'),
      exportBackupConfirmTitle: t('exportBackupConfirmTitle'),
      exportBackupConfirmBody: t('exportBackupConfirmBody'),
      backupPassword: t('backupPassword'),
      backupPasswordOptional: t('backupPasswordOptional'),
      backupPasswordConfirm: t('backupPasswordConfirm'),
      backupPasswordHint: t('backupPasswordHint'),
      backupPasswordProtected: t('backupPasswordProtected'),
      backupPasswordMismatch: t('backupPasswordMismatch'),
      exportBackupCancel: t('exportBackupCancel'),
      exportBackupSubmit: t('exportBackupSubmit'),
      backupExportDone: (path: string) => t('backupExportDone', { path }),
      backupImportDone: (count: number) => t('backupImportDone', { count }),
      backupActionFailed: (reason: string) => t('backupActionFailed', { reason }),
      importBackupConfirmTitle: t('importBackupConfirmTitle'),
      importBackupConfirmBody: t('importBackupConfirmBody'),
      importBackupConfirmHint: t('importBackupConfirmHint'),
      importBackupCurrentStats: (cues: number, resources: number, tags: number) =>
        t('importBackupCurrentStats', { cues, resources, tags }),
      importBackupCancel: t('importBackupCancel'),
      importBackupSubmit: t('importBackupSubmit'),
      importBackupBlocked: t('importBackupBlocked'),
      importBackupUnavailable: t('importBackupUnavailable'),
      importBackupPasswordRequired: t('importBackupPasswordRequired'),
      importBackupProtectedHint: t('importBackupProtectedHint'),
      backupVersionSummary: (backupVersion: number, backupSchema: number, currentSchema: number) =>
        t('backupVersionSummary', { backupVersion, backupSchema, currentSchema }),
      backupSelectedPath: (path: string) => t('backupSelectedPath', { path }),
      backupCompatibilityReady: t('backupCompatibilityReady'),
      backupCompatibilityFormatTooNew: t('backupCompatibilityFormatTooNew'),
      backupCompatibilityFormatLegacy: t('backupCompatibilityFormatLegacy'),
      backupCompatibilitySchemaTooNew: t('backupCompatibilitySchemaTooNew'),
      backupCompatibilitySchemaLegacy: t('backupCompatibilitySchemaLegacy'),
      backupCompatibilityStorageModeChanged: t('backupCompatibilityStorageModeChanged'),
      backupCompatibilityUnknown: t('backupCompatibilityUnknown'),
      backupIntegrityReady: t('backupIntegrityReady'),
      backupIntegrityFailed: t('backupIntegrityFailed'),
      backupIntegrityHint: t('backupIntegrityHint'),
      backupIntegrityPackageCorrupt: t('backupIntegrityPackageCorrupt'),
      backupIntegrityDatabaseMismatch: t('backupIntegrityDatabaseMismatch'),
      backupIntegrityLibraryMismatch: t('backupIntegrityLibraryMismatch'),
      backupIntegrityWaveformMismatch: t('backupIntegrityWaveformMismatch'),
      backupIntegrityTrashMismatch: t('backupIntegrityTrashMismatch'),
      backupIntegrityPasswordRequired: t('backupIntegrityPasswordRequired'),
      backupIntegrityPasswordOrSignatureInvalid: t('backupIntegrityPasswordOrSignatureInvalid'),
      backupIntegrityEncryptedPayloadCorrupt: t('backupIntegrityEncryptedPayloadCorrupt'),
      backupIntegrityUnknown: t('backupIntegrityUnknown'),
      backupDiffTitle: t('backupDiffTitle'),
      backupDiffHint: t('backupDiffHint'),
      backupDiffUnavailable: t('backupDiffUnavailable'),
      backupDiffSectionCues: t('backupDiffSectionCues'),
      backupDiffSectionTags: t('backupDiffSectionTags'),
      backupDiffSectionResources: t('backupDiffSectionResources'),
      backupDiffCounts: (current: number, backup: number, shared: number) =>
        t('backupDiffCounts', { current, backup, shared }),
      backupDiffIncomingOnly: (count: number) => t('backupDiffIncomingOnly', { count }),
      backupDiffCurrentOnly: (count: number) => t('backupDiffCurrentOnly', { count }),
      backupDiffShared: (count: number) => t('backupDiffShared', { count }),
      backupDiffShowDetails: t('backupDiffShowDetails'),
      backupDiffHideDetails: t('backupDiffHideDetails'),
      backupDiffSearch: t('backupDiffSearch'),
      backupDiffSearchPlaceholder: t('backupDiffSearchPlaceholder'),
      backupDiffNoMatches: t('backupDiffNoMatches'),
      backupDiffNoResults: (keyword: string) => t('backupDiffNoResults', { keyword }),
      backupDiffExportFormat: (format: string) => t('backupDiffExportFormat', { format }),
      backupDiffExportDone: (format: string, path: string) => t('backupDiffExportDone', { format, path }),
      backupDiffSummaryTitle: t('backupDiffSummaryTitle'),
      backupDiffSummaryBySection: t('backupDiffSummaryBySection'),
      backupDiffSummaryKeywordNone: t('backupDiffSummaryKeywordNone'),
      backupDiffSummarySections: (matched: number, total: number) =>
        t('backupDiffSummarySections', { matched, total }),
      backupDiffSummaryTotals: (
        current: number,
        backup: number,
        incomingOnly: number,
        currentOnly: number,
        shared: number,
      ) =>
        t('backupDiffSummaryTotals', {
          current,
          backup,
          incomingOnly,
          currentOnly,
          shared,
        }),
      backupDiffSummarySection: (
        title: string,
        current: number,
        backup: number,
        incomingOnly: number,
        currentOnly: number,
        shared: number,
      ) =>
        t('backupDiffSummarySection', {
          title,
          current,
          backup,
          incomingOnly,
          currentOnly,
          shared,
        }),
      backupDiffExcludedCount: (count: number) => t('backupDiffExcludedCount', { count }),
      backupDiffClearExcluded: t('backupDiffClearExcluded'),
      backupDiffTemplateTitle: t('backupDiffTemplateTitle'),
      backupDiffTemplateHint: t('backupDiffTemplateHint'),
      backupDiffTemplateName: t('backupDiffTemplateName'),
      backupDiffTemplatePlaceholder: t('backupDiffTemplatePlaceholder'),
      backupDiffTemplateSave: t('backupDiffTemplateSave'),
      backupDiffTemplateDelete: t('backupDiffTemplateDelete'),
      backupDiffTemplateEmpty: t('backupDiffTemplateEmpty'),
      backupDiffTemplateSaved: (name: string) => t('backupDiffTemplateSaved', { name }),
      backupDiffTemplateApplied: (name: string) => t('backupDiffTemplateApplied', { name }),
      backupDiffTemplateDeleted: (name: string) => t('backupDiffTemplateDeleted', { name }),
      diagnostics: t('diagnostics'),
      diagnosticsHealthy: t('diagnosticsHealthy'),
      clearDiagnostics: t('clearDiagnostics'),
      hotkeyRepairDiagnostic: (count: number) => t('hotkeyRepairDiagnostic', { count }),
      hotkeyRepairDiagnosticHint: t('hotkeyRepairDiagnosticHint'),
      missingFilesDiagnostic: (count: number) => t('missingFilesDiagnostic', { count }),
      missingFilesDiagnosticHint: t('missingFilesDiagnosticHint'),
      deviceUnsupportedDiagnostic: (count: number) => t('deviceUnsupportedDiagnostic', { count }),
      deviceUnsupportedDiagnosticHint: t('deviceUnsupportedDiagnosticHint'),
      deviceFallbackDiagnostic: (count: number) => t('deviceFallbackDiagnostic', { count }),
      deviceFallbackDiagnosticHint: t('deviceFallbackDiagnosticHint'),
      playbackFailureDiagnostic: (count: number) => t('playbackFailureDiagnostic', { count }),
      playbackFailureDiagnosticHint: (name: string) => t('playbackFailureDiagnosticHint', { name }),
      allTags: t('allTags'),
      play: t('play'),
      pauseAll: t('pauseAll'),
      resumeAll: t('resumeAll'),
      stopAll: t('stopAll'),
      masterVolume: t('masterVolume'),
      activeCount: (count: number) => t('activeCount', { count }),
      missingCount: (count: number) => t('missingCount', { count }),
      hotkeyAlerts: (count: number) => t('hotkeyAlerts', { count }),
      runtimeIssues: (count: number) => t('runtimeIssues', { count }),
      library: t('library'),
      soundsReady: (count: number) => t('soundsReady', { count }),
      visibleRange: (start: number, end: number, total: number) =>
        t('visibleRange', { start, end, total }),
      rescanFiles: t('rescanFiles'),
      managementCenter: t('managementCenter'),
      managementCenterHint: t('managementCenterHint'),
      openManagementCenter: t('openManagementCenter'),
      closeManagementCenter: t('closeManagementCenter'),
      resourceMaintenance: t('resourceMaintenance'),
      resourceMaintenanceHint: t('resourceMaintenanceHint'),
      floatingControl: t('floatingControl'),
      floatingControlHint: t('floatingControlHint'),
      openFloatingControl: t('openFloatingControl'),
      showMainBoard: t('showMainBoard'),
      viewPaged: t('viewPaged'),
      viewVirtual: t('viewVirtual'),
      boardMode: (mode: string) => t('boardMode', { mode }),
      pageSize: t('pageSize'),
      pageInfo: (page: number, total: number) => t('pageInfo', { page, total }),
      prevPage: t('prevPage'),
      nextPage: t('nextPage'),
      virtualWindowInfo: (rows: number, totalRows: number) =>
        t('virtualWindowInfo', { rows, totalRows }),
      missingWarning: (count: number) => t('missingWarning', { count }),
      duplicateWarning: (duplicates: number, failed: number) =>
        `${duplicates > 0 ? `${t('duplicateWarningDuplicates', { count: duplicates })} ` : ''}${failed > 0 ? t('duplicateWarningFailed', { count: failed }) : ''}`.trim(),
      nowPlaying: t('nowPlaying'),
      layeredPlayback: (count: number) => t('layeredPlayback', { count }),
      pausedSuffix: t('pausedSuffix'),
      editCue: t('editCue'),
      closePanel: t('closePanel'),
      advancedSettings: t('advancedSettings'),
      dangerZone: t('dangerZone'),
      missingFile: t('missingFile'),
      duplicateHotkey: t('duplicateHotkey'),
      rejectedHotkey: t('rejectedHotkey'),
      noSoundsTitle: t('noSoundsTitle'),
      noSoundsBody: t('noSoundsBody'),
      settings: t('settings'),
      playbackRouting: t('playbackRouting'),
      language: t('language'),
      languageZh: t('languageZh'),
      languageEn: t('languageEn'),
      allowLayeredPlayback: t('allowLayeredPlayback'),
      stopOthersOnTrigger: t('stopOthersOnTrigger'),
      warnOnMissingFiles: t('warnOnMissingFiles'),
      globalShortcutsEnabled: t('globalShortcutsEnabled'),
      hotkeySuggestionSettings: t('hotkeySuggestionSettings'),
      hotkeySuggestionPrimaryModifier: t('hotkeySuggestionPrimaryModifier'),
      hotkeySuggestionIncludeAlternateModifiers: t('hotkeySuggestionIncludeAlternateModifiers'),
      hotkeySuggestionIncludeDigits: t('hotkeySuggestionIncludeDigits'),
      hotkeySuggestionIncludeFunctionKeys: t('hotkeySuggestionIncludeFunctionKeys'),
      hotkeySuggestionIncludeLetters: t('hotkeySuggestionIncludeLetters'),
      hotkeySuggestionGroupingMode: t('hotkeySuggestionGroupingMode'),
      hotkeySuggestionGroupingNone: t('hotkeySuggestionGroupingNone'),
      hotkeySuggestionGroupingTag: t('hotkeySuggestionGroupingTag'),
      outputDevice: t('outputDevice'),
      systemDefaultOutput: t('systemDefaultOutput'),
      outputDeviceFallback: (index: number) => t('outputDeviceFallback', { index }),
      inspector: t('inspector'),
      selectSound: t('selectSound'),
      inspectorHint: t('inspectorHint'),
      name: t('name'),
      hotkey: t('hotkey'),
      hotkeyPlaceholder: t('hotkeyPlaceholder'),
      tags: t('tags'),
      tagsPlaceholder: t('tagsPlaceholder'),
      speed: t('speed'),
      cueVolume: t('cueVolume'),
      sourceFile: t('sourceFile'),
      preview: t('preview'),
      remove: t('remove'),
      deleteConfirmTitle: t('deleteConfirmTitle'),
      deleteConfirmBody: (name: string) => t('deleteConfirmBody', { name }),
      deleteConfirmHint: t('deleteConfirmHint'),
      deleteConfirmCancel: t('deleteConfirmCancel'),
      deleteConfirmSubmit: t('deleteConfirmSubmit'),
      chooseSoundHint: t('chooseSoundHint'),
      noHotkey: t('noHotkey'),
      untagged: t('untagged'),
      ready: t('ready'),
      playbackStopped: t('playbackStopped'),
      allPlaybackStopped: t('allPlaybackStopped'),
      queueCleared: (name: string) => t('queueCleared', { name }),
      selectedOutputFallback: t('selectedOutputFallback'),
      playMissing: (name: string) => t('playMissing', { name }),
      playFileMissing: (name: string) => t('playFileMissing', { name }),
      playDeviceFailed: (name: string) => t('playDeviceFailed', { name }),
      playing: (name: string) => t('playing', { name }),
      allResumed: t('allResumed'),
      allPaused: t('allPaused'),
      imported: (count: number) => t('imported', { count }),
      importEmpty: t('importEmpty'),
      allFilesAvailable: t('allFilesAvailable'),
      filesMissing: (count: number) => t('filesMissing', { count }),
      waveform: t('waveform'),
      waveformLoading: t('waveformLoading'),
      trimStart: t('trimStart'),
      trimEnd: t('trimEnd'),
      trimUntilEnd: t('trimUntilEnd'),
      segmentDuration: t('segmentDuration'),
      hotkeyRecord: t('hotkeyRecord'),
      hotkeyRecording: t('hotkeyRecording'),
      hotkeyClear: t('hotkeyClear'),
      resourceName: t('resourceName'),
      managedDataRoot: t('managedDataRoot'),
      waveformCache: t('waveformCache'),
      trashDirectory: t('trashDirectory'),
      storageModeInstalled: t('storageModeInstalled'),
      storageModePortable: t('storageModePortable'),
      resourcesStat: (count: number) => t('resourcesStat', { count }),
      orphanStat: (count: number) => t('orphanStat', { count }),
      addTag: t('addTag'),
      tagColors: t('tagColors'),
      resetAutoColor: t('resetAutoColor'),
      importReportTitle: t('importReportTitle'),
      importFailures: t('importFailures'),
      importScanning: t('importScanning'),
      importProgressSummary: (
        completed: number,
        total: number,
        imported: number,
        failed: number,
      ) => t('importProgressSummary', { completed, total, imported, failed }),
      importCurrentFile: (path: string) => t('importCurrentFile', { path }),
      importRetryAll: t('importRetryAll'),
      importRetryOne: t('importRetryOne'),
      importFailurePathMissing: t('importFailurePathMissing'),
      importFailurePermissionDenied: t('importFailurePermissionDenied'),
      importFailureUnsupportedType: t('importFailureUnsupportedType'),
      importFailureDirectoryScanFailed: t('importFailureDirectoryScanFailed'),
      importFailureHashFailed: t('importFailureHashFailed'),
      importFailureMetadataReadFailed: t('importFailureMetadataReadFailed'),
      importFailureLibraryCopyFailed: t('importFailureLibraryCopyFailed'),
      importFailureDatabaseWriteFailed: t('importFailureDatabaseWriteFailed'),
      importFailureUnknown: t('importFailureUnknown'),
      importFailureReason: (reason: string) => t('importFailureReason', { reason }),
      importFailureNotRetryable: t('importFailureNotRetryable'),
      onboardingTitle: t('onboardingTitle'),
      onboardingBody: t('onboardingBody'),
      onboardingStepImport: t('onboardingStepImport'),
      onboardingStepEdit: t('onboardingStepEdit'),
      onboardingStepTrigger: t('onboardingStepTrigger'),
      starterPackReady: (count: number) => t('starterPackReady', { count }),
      importSummary: (
        cues: number,
        resources: number,
        reused: number,
        failed: number,
        duplicates: number,
        invalid: number,
      ) =>
        t('importSummary', {
          cues,
          resources,
          reused,
          failed,
          duplicates,
          invalid,
        }),
      cleanupSummary: (resources: number, tags: number) => t('cleanupSummary', { resources, tags }),
      cleanupUnused: t('cleanupUnused'),
      cleanupConfirmTitle: t('cleanupConfirmTitle'),
      cleanupConfirmBody: t('cleanupConfirmBody'),
      cleanupConfirmStats: (count: number) => t('cleanupConfirmStats', { count }),
      cleanupConfirmCancel: t('cleanupConfirmCancel'),
      cleanupConfirmSubmit: t('cleanupConfirmSubmit'),
      cleanupDone: (resources: number, tags: number) => t('cleanupDone', { resources, tags }),
      selectedCount: (count: number) => t('selectedCount', { count }),
      clearSelection: t('clearSelection'),
      bulkTags: t('bulkTags'),
      bulkTagPlaceholder: t('bulkTagPlaceholder'),
      bulkAdd: t('bulkAdd'),
      bulkRemove: t('bulkRemove'),
      bulkReplace: t('bulkReplace'),
      bulkClearAll: t('bulkClearAll'),
      bulkTagInventory: t('bulkTagInventory'),
      bulkTagInventoryHint: t('bulkTagInventoryHint'),
      bulkTagCommon: t('bulkTagCommon'),
      bulkTagCommonHint: t('bulkTagCommonHint'),
      bulkUseCommon: t('bulkUseCommon'),
      bulkRemoveSelectedTag: t('bulkRemoveSelectedTag'),
      bulkNoTags: t('bulkNoTags'),
      tagManager: t('tagManager'),
      tagManagerTitle: (count: number) => t('tagManagerTitle', { count }),
      tagManagerHint: t('tagManagerHint'),
      tagManagerSearch: t('tagManagerSearch'),
      tagManagerSearchPlaceholder: t('tagManagerSearchPlaceholder'),
      tagManagerSort: t('tagManagerSort'),
      tagManagerSortName: t('tagManagerSortName'),
      tagManagerSortUsage: t('tagManagerSortUsage'),
      tagManagerSortRecent: t('tagManagerSortRecent'),
      tagManagerUsage: (count: number) => t('tagManagerUsage', { count }),
      tagManagerEmpty: t('tagManagerEmpty'),
      tagManagerRename: t('tagManagerRename'),
      tagManagerRenameApply: t('tagManagerRenameApply'),
      tagManagerDelete: t('tagManagerDelete'),
      tagManagerRenameDone: (from: string, to: string) => t('tagManagerRenameDone', { from, to }),
      tagManagerDeleteDone: (name: string) => t('tagManagerDeleteDone', { name }),
      tagManagerDeleteConfirm: (name: string, count: number) =>
        t('tagManagerDeleteConfirm', { name, count }),
      tagManagerSelectFiltered: t('tagManagerSelectFiltered'),
      tagManagerClearSelection: t('tagManagerClearSelection'),
      tagManagerSelectedCount: (count: number) => t('tagManagerSelectedCount', { count }),
      tagManagerBatchTools: t('tagManagerBatchTools'),
      tagManagerBatchMerge: t('tagManagerBatchMerge'),
      tagManagerBatchMergeHint: t('tagManagerBatchMergeHint'),
      tagManagerBatchMergeDone: (count: number, target: string) =>
        t('tagManagerBatchMergeDone', { count, target }),
      tagManagerBatchColor: t('tagManagerBatchColor'),
      tagManagerBatchColorDone: (count: number) => t('tagManagerBatchColorDone', { count }),
      tagManagerBatchResetColor: t('tagManagerBatchResetColor'),
      tagManagerBatchColorResetDone: (count: number) => t('tagManagerBatchColorResetDone', { count }),
      tagManagerBatchDelete: t('tagManagerBatchDelete'),
      tagManagerBatchDeleteConfirm: (count: number) => t('tagManagerBatchDeleteConfirm', { count }),
      tagManagerBatchDeleteDone: (count: number) => t('tagManagerBatchDeleteDone', { count }),
      tagManagerBatchRenameRule: t('tagManagerBatchRenameRule'),
      tagManagerBatchRenameFind: t('tagManagerBatchRenameFind'),
      tagManagerBatchRenameReplace: t('tagManagerBatchRenameReplace'),
      tagManagerBatchRenamePrefix: t('tagManagerBatchRenamePrefix'),
      tagManagerBatchRenameSuffix: t('tagManagerBatchRenameSuffix'),
      tagManagerBatchRenameCase: t('tagManagerBatchRenameCase'),
      tagManagerBatchRenameCasePreserve: t('tagManagerBatchRenameCasePreserve'),
      tagManagerBatchRenameCaseLower: t('tagManagerBatchRenameCaseLower'),
      tagManagerBatchRenameCaseUpper: t('tagManagerBatchRenameCaseUpper'),
      tagManagerBatchRenameCaseTitle: t('tagManagerBatchRenameCaseTitle'),
      tagManagerBatchRenameTrim: t('tagManagerBatchRenameTrim'),
      tagManagerBatchRenameCollapseSpaces: t('tagManagerBatchRenameCollapseSpaces'),
      tagManagerBatchRenameApply: (count: number) => t('tagManagerBatchRenameApply', { count }),
      tagManagerBatchRenameReset: t('tagManagerBatchRenameReset'),
      tagManagerBatchRenameDone: (count: number) => t('tagManagerBatchRenameDone', { count }),
      tagManagerBatchRenameEmptyPreview: t('tagManagerBatchRenameEmptyPreview'),
      tagManagerBatchRenameWarningsTitle: t('tagManagerBatchRenameWarningsTitle'),
      tagManagerBatchRenameWarningEmpty: (count: number) =>
        t('tagManagerBatchRenameWarningEmpty', { count }),
      tagManagerBatchRenameWarningUnchanged: (count: number) =>
        t('tagManagerBatchRenameWarningUnchanged', { count }),
      tagManagerBatchRenameWarningMergeExisting: (count: number) =>
        t('tagManagerBatchRenameWarningMergeExisting', { count }),
      tagManagerBatchRenameWarningMergeSelection: (count: number) =>
        t('tagManagerBatchRenameWarningMergeSelection', { count }),
      dragSortHint: t('dragSortHint'),
      reservedHotkey: t('reservedHotkey'),
      weakHotkey: t('weakHotkey'),
      hotkeyRepair: t('hotkeyRepair'),
      hotkeyRepairOpen: t('hotkeyRepairOpen'),
      hotkeyRepairTitle: t('hotkeyRepairTitle'),
      hotkeyRepairHint: t('hotkeyRepairHint'),
      hotkeyRepairScopeDuplicate: t('hotkeyRepairScopeDuplicate'),
      hotkeyRepairScopeFailed: t('hotkeyRepairScopeFailed'),
      hotkeyRepairScopeReserved: t('hotkeyRepairScopeReserved'),
      hotkeyRepairScopeWeak: t('hotkeyRepairScopeWeak'),
      hotkeyRepairSelection: (count: number) => t('hotkeyRepairSelection', { count }),
      hotkeyRepairCancel: t('hotkeyRepairCancel'),
      hotkeyRepairClear: t('hotkeyRepairClear'),
      hotkeyRepairAssign: t('hotkeyRepairAssign'),
      hotkeyRepairAssigned: (count: number) => t('hotkeyRepairAssigned', { count }),
      hotkeyRepairCleared: (count: number) => t('hotkeyRepairCleared', { count }),
      hotkeyRepairFailed: (reason: string) => t('hotkeyRepairFailed', { reason }),
      hotkeySuggestionTitle: (count: number) => t('hotkeySuggestionTitle', { count }),
      hotkeySuggestionHint: t('hotkeySuggestionHint'),
      hotkeySuggestionApply: t('hotkeySuggestionApply'),
      hotkeySuggestionSelection: (count: number) => t('hotkeySuggestionSelection', { count }),
      hotkeySuggestionApplied: (count: number) => t('hotkeySuggestionApplied', { count }),
      hotkeySuggestionFailed: (reason: string) => t('hotkeySuggestionFailed', { reason }),
      history: t('history'),
      historyPolicy: (max: number, activeDays: number, undoneDays: number) =>
        t('historyPolicy', { max, activeDays, undoneDays }),
      undo: t('undo'),
      undoDone: (summary: string) => t('undoDone', { summary }),
      historyUndone: (time: string) => t('historyUndone', { time }),
      noHistory: t('noHistory'),
    }),
    [t],
  )
}
